{application,live_vue,
             [{modules,['Elixir.LiveVue','Elixir.LiveVue.Components',
                        'Elixir.LiveVue.Reload','Elixir.LiveVue.SSR',
                        'Elixir.LiveVue.SSR.NodeJS',
                        'Elixir.LiveVue.SSR.NotConfigured',
                        'Elixir.LiveVue.SSR.ViteJS','Elixir.LiveVue.Slots',
                        'Elixir.Mix.Tasks.LiveVue.Setup']},
              {compile_env,[{live_vue,[ssr],{ok,true}}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jason,nodejs,phoenix,
                             phoenix_live_view,telemetry]},
              {description,"E2E reactivity for Vue and LiveView"},
              {registered,[]},
              {vsn,"0.5.7"}]}.
