import { Component } from "vue";
import { LiveVueOptions } from "./types.js";
type Components = Record<string, Component>;
type Manifest = Record<string, string[]>;
export declare const getRender: (componentsOrApp: Components | LiveVueOptions, manifest?: Manifest) => (name: string, props: Record<string, any>, slots: Record<string, string>) => Promise<string>;
/**
 * Loads the manifest file from the given path and returns a record of the assets.
 * Manifest file is a JSON file generated by Vite for the client build.
 * We need to load it to know which files to preload for the given page.
 * @param path - The path to the manifest file.
 * @returns A record of the assets.
 */
export declare const loadManifest: (path: string) => Record<string, string[]>;
export {};
