{application,ssl_verify_fun,
             [{modules,[ssl_verify_fingerprint,ssl_verify_fun_cert_helpers,
                        ssl_verify_fun_encodings,ssl_verify_hostname,
                        ssl_verify_pk,ssl_verify_string,ssl_verify_util]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,ssl]},
              {registered,[]},
              {description,"SSL verification library"},
              {vsn,"1.1.7"},
              {env,[]}]}.
