defmodule LiveVue.SSR.QuickJS do
  @moduledoc """
  Implements SSR using an embedded QuickJS-NG JavaScript engine via `quickjs_ex`.

  Unlike `LiveVue.SSR.NodeJS`, this module runs JavaScript inside the BEAM process
  via a NIF — no external Node.js installation required. This simplifies deployment
  (no Node.js in Docker images) while keeping SSR fully functional.

  ## Setup

  Add `quickjs_ex` to your dependencies:

      {:quickjs_ex, "~> 0.1.0"}

  Configure your application:

      # config/prod.exs
      config :live_vue,
        ssr_module: LiveVue.SSR.QuickJS

  Add the module to your supervision tree in `application.ex`:

      children = [
        LiveVue.SSR.QuickJS,
        # ...
      ]

  The module loads the SSR bundle from the path configured via `:ssr_filepath`
  (default `"./static/server.mjs"`), relative to the application's `priv` directory.

  ## How It Works

  On startup, the module:

  1. Starts a QuickJS-NG runtime on a dedicated OS thread
  2. Installs polyfills for globals that the Vite SSR bundle expects
     (`process`, `Buffer`, `atob`/`btoa`, `window`, `document`, etc.)
  3. Rewrites Node.js-style `import`/`export` statements in the bundle
     to work in a plain script context
  4. Evaluates the adapted bundle, making the `render` function available

  Each `render/3` call invokes the JS `render` function. Promises returned
  by `renderToString` are automatically awaited by `quickjs_ex`.
  """

  @behaviour LiveVue.SSR

  @polyfills """
  globalThis.process = { env: { NODE_ENV: 'production' } };

  (function() {
    var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
    globalThis.btoa = function(input) {
      var str = String(input);
      var output = '';
      for (var block, charCode, idx = 0, map = chars;
           str.charAt(idx | 0) || (map = '=', idx % 1);
           output += map.charAt(63 & block >> 8 - idx % 1 * 8)) {
        charCode = str.charCodeAt(idx += 3/4);
        block = block << 8 | charCode;
      }
      return output;
    };
    globalThis.atob = function(input) {
      var str = String(input).replace(/=+$/, '');
      var output = '';
      for (var bs = 0, buffer, bc = 0;
           buffer = str.charAt(bc++);
           ~buffer && (bs = bc % 4 ? bs * 64 + buffer : buffer, bc % 4) ?
             output += String.fromCharCode(255 & bs >> (-2 * bc & 6)) : 0) {
        buffer = chars.indexOf(buffer);
      }
      return output;
    };
  })();

  globalThis.Buffer = {
    from: function(str, encoding) {
      if (encoding === 'base64') {
        var decoded = atob(str);
        return { toString: function() { return decoded; } };
      }
      return { toString: function() { return String(str); } };
    }
  };

  globalThis.URL = globalThis.URL || function(url) { this.href = url; };
  globalThis.window = globalThis;
  globalThis.document = { querySelector: function() { return null; }, createElement: function() { return {}; } };
  globalThis.navigator = { userAgent: '' };
  globalThis.self = globalThis;
  undefined;
  """

  def child_spec(opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [opts]},
      type: :worker
    }
  end

  def start_link(_opts \\ []) do
    {:ok, rt} = QuickJSEx.start(name: __MODULE__)
    load_bundle(rt)
    {:ok, rt}
  end

  @impl true
  def render(name, props, slots) do
    case QuickJSEx.call(__MODULE__, "render", [name, props, slots]) do
      {:ok, html} ->
        html

      {:error, reason} ->
        raise "QuickJS SSR render failed for #{name}: #{reason}"
    end
  end

  defp load_bundle(rt) do
    eval!(rt, @polyfills)

    bundle =
      ssr_filepath()
      |> File.read!()
      |> adapt_for_quickjs()

    eval!(rt, bundle)
  end

  defp eval!(rt, code) do
    case QuickJSEx.eval(rt, code) do
      {:ok, _} ->
        :ok

      {:error, "Value is not JSON-serializable"} ->
        :ok

      {:error, "JSON stringify error: Exception generated by QuickJS"} ->
        :ok

      {:error, reason} ->
        raise "QuickJS SSR bundle evaluation failed: #{reason}"
    end
  end

  defp ssr_filepath do
    {:ok, app} = :application.get_application()
    filepath = Application.get_env(:live_vue, :ssr_filepath, "./static/server.mjs")
    Application.app_dir(app, Path.join("priv", filepath))
  end

  defp adapt_for_quickjs(code) do
    LiveVue.SSR.QuickJS.BundleAdapter.adapt(code)
  end
end
