defmodule LiveVue.SSR.QuickJS do
  @moduledoc """
  Implements SSR using an embedded QuickJS-NG JavaScript engine via `quickjs_ex`.

  Unlike `LiveVue.SSR.NodeJS`, this module runs JavaScript inside the BEAM
  process via a NIF — no external Node.js installation required.

  ## Setup

  1. Add `quickjs_ex` to your dependencies:

      ```elixir
      {:quickjs_ex, "~> 0.1.1"}
      ```

  2. Add the `stubNodeBuiltins` Vite plugin to your `vite.config`:

      ```javascript
      import stubNodeBuiltins from "live_vue/stubNodeBuiltins"

      export default defineConfig({
        plugins: [vue(), liveVuePlugin(), stubNodeBuiltins()],
      })
      ```

     This replaces Node.js built-in imports (`fs`, `path`, `node:stream`) with
     stubs at build time, producing a self-contained SSR bundle.

  3. Configure production SSR:

      ```elixir
      # config/prod.exs
      config :live_vue,
        ssr_module: LiveVue.SSR.QuickJS
      ```

  4. Add to your supervision tree in `application.ex`:

      ```elixir
      children = [
        LiveVue.SSR.QuickJS,
        # ...
      ]
      ```

  The module loads the SSR bundle from the path configured via `:ssr_filepath`
  (default `"./static/server.mjs"`), relative to the application's `priv` directory.
  """

  @behaviour LiveVue.SSR

  @polyfills """
  globalThis.process = { env: { NODE_ENV: 'production' } };
  globalThis.URL = globalThis.URL || function(url) { this.href = url; };
  globalThis.window = globalThis;
  globalThis.document = { querySelector: function() { return null; }, createElement: function() { return {}; } };
  globalThis.navigator = { userAgent: '' };
  globalThis.self = globalThis;
  undefined;
  """

  def child_spec(opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [opts]},
      type: :worker
    }
  end

  def start_link(_opts \\ []) do
    {:ok, rt} = QuickJSEx.start(name: __MODULE__)
    load_bundle(rt)
    {:ok, rt}
  end

  @impl true
  def render(name, props, slots) do
    case QuickJSEx.call(__MODULE__, "render", [name, props, slots]) do
      {:ok, html} ->
        html

      {:error, reason} ->
        raise "QuickJS SSR render failed for #{name}: #{reason}"
    end
  end

  defp load_bundle(rt) do
    eval!(rt, @polyfills)

    ssr_filepath()
    |> File.read!()
    |> then(&eval!(rt, &1))
  end

  defp eval!(rt, code) do
    case QuickJSEx.eval(rt, code) do
      {:ok, _} ->
        :ok

      {:error, "Value is not JSON-serializable"} ->
        :ok

      {:error, "JSON stringify error: Exception generated by QuickJS"} ->
        :ok

      {:error, reason} ->
        raise "QuickJS SSR bundle evaluation failed: #{reason}"
    end
  end

  defp ssr_filepath do
    {:ok, app} = :application.get_application()
    filepath = Application.get_env(:live_vue, :ssr_filepath, "./static/server.mjs")
    Application.app_dir(app, Path.join("priv", filepath))
  end
end
