name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-24.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.15"
            otp: "25"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.18"
            otp: "28"

    steps:
      - uses: actions/checkout@v5
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependency cache
        uses: actions/cache@v4
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-
      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Install phx_new
        run: mix archive.install hex phx_new 1.8.0 --force
      - name: Compile application
        run: mix compile
      - name: Run tests
        run: mix test
      - name: Run tests and coverage
        if: matrix.elixir == '1.17' && matrix.otp == '27'
        run: mix coveralls.github
